### ISSUE TITLE
Add support for Microsoft Entra ID authentication

### ISSUE THREAD

**Issue by goldsam** [tnc1997/azure-app-configuration-emulator#76]
My organization has many applications which are configured/restricted to use only Azure Entra (Specifically client secret) authentication when accessing any Azure service. We strive to test our applications in as similar an environment as productions as is possible without creating test-only code paths. Thus, it would be beneficial to authenticate with your app configuration emulator either using Entra auth or to be able to disable authentication requirements entirely.

**Comment by tnc1997** [comment]
Hi @goldsam, thank you for your feature request!

Could I ask you to clone the branch `feat/76` and test the Microsoft Entra ID authentication scheme?

**Comment by goldsam** [comment]
I would be happy to, but I may not have time until this coming weekend.

**Comment by goldsam** [comment]
I've been testing branch 'feat/76', and I have some feedback:
- I would recommend removing the following two lines:
    https://github.com/tnc1997/azure-app-configuration-emulator/blob/fa6514cec07d8a0a61eaf9c07cd5a86bc015e090/src/AzureAppConfigurationEmulator/Program.cs#L37-L38

   My justification is:
   - [`ValidateAudience`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateaudience?view=msal-web-dotnet-latest#remarks) and [`ValidateIssuer`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateissuer?view=msal-web-dotnet-latest#remarks) are `true` by default.
   - Overriding them in this manner prevents a user from setting them to `false` should they want to.

- Using the official [`ConfigurationClient`](https://learn.microsoft.com/en-us/dotnet/api/azure.data.appconfiguration.configurationclient?view=azure-dotnet) with Entra Id authentication turned out to be non-trivial. I had solve the following challenges:

  - Both [`ClientSecretCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.clientsecretcredential?view=azure-dotnet) and [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) will attempt to use the emulator's base address as the *resource principal name* passed to Entra Id via the OAuth scope parameter when authenticating. This failed with the following exception:

    ```
    Azure.Identity.AuthenticationFailedException : ClientSecretCredential authentication failed: AADSTS500011: The resource principal named https://127.0.0.1:56052 was not found in the tenant named [REDACTED]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: [REDACTED] Correlation ID: [REDACTED] Timestamp: 2024-06-06 21:50:35Z
    ```

    My solution was:

    1. [Set an Application ID URI for my application registration](https://learn.microsoft.com/en-us/entra/identity-platform/security-best-practices-for-app-registration#application-id-uri). I used a URI of the form `api://<appId>`.

    2. Create a custom [`TokenCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet) decorator/wrapper to override the scopes passed when requesting a token. The actual token is acquired through a wrapped/delegate `TokenCredential` (such as `ClientSecretCredential`):
    
       > **NOTE**: The scope I used successfully was of the form `api://<appId>/.default`.

        Below is my `TokenCredential` wrapper class:

        ```csharp
        using Azure.Core;
        using Microsoft.Extensions.Configuration;

        class ScopesOverridingTokenCredential : TokenCredential
        {
            private readonly TokenCredential _innerTokenCredential;
            private readonly string[] _scopes;

            public ScopesOverridingTokenCredential(TokenCredential innerTokenCredential, params string[] scopes)
                : this(innerTokenCredential, scopes.AsEnumerable())
            { }

            public ScopesOverridingTokenCredential(TokenCredential innerTokenCredential, IEnumerable<string> scopes)
            {
                _innerTokenCredential = innerTokenCredential;
                _scopes = scopes as string[] ?? scopes.ToArray();
            }

            public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) =>
                _innerTokenCredential.GetToken(CreateModifiedTokenRequestContext(requestContext), cancellationToken);
            
            public override async ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken) =>
                await _innerTokenCredential.GetTokenAsync(CreateModifiedTokenRequestContext(requestContext), cancellationToken);
            
            private TokenRequestContext CreateModifiedTokenRequestContext(TokenRequestContext requestContext) =>
                new TokenRequestContext(_scopes, requestContext.ParentRequestId, requestContext.Claims, requestContext.TenantId, requestContext.IsCaeEnabled);   
        }
        ```

        I would love to find a better way to solve this issue.

  - `ConfigurationClient` [refuses to connect to a URI endpoint over an unsecured HTTP connection](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L115-L117). 
  
     This behavior cannot be overridden since: 
     
     1. The `ConfigurationClient(Uri endpoint, TokenCredential credential, ConfigurationClientOptions options)` constructor [hardcodes the use of a `BearerTokenAuthenticationPolicy`](https://github.com/Azure/azure-sdk-for-net/blob/05dccb316a38fe5b577fbade158a2027237dc8b1/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L70-L87).
     2. class `BearerTokenAuthenticationPolicy` [hardcodes a check that the target service URL uses the `https` URI scheme](https://github.com/Azure/azure-sdk-for-net/blob/05dccb316a38fe5b577fbade158a2027237dc8b1/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L114-L118) when using a endpoint `Uri`.

     Thus, I was forced to deploy the emulator with TLS enabled. 

     To achieve this, I dynamically provisioned a self-signed certificate which is mounted into the running `azure-app-configuration-emulator` container and configured for use via env-var config.

     > **NOTE**: My team uses [TestContainers](https://github.com/testcontainers/testcontainers-dotnet) for orchestrating our integration tests (often consisting of several containers) for which have created custom extensions to simplify the setup described above. It might be worth publishing a [TestContainer *module*](https://dotnet.testcontainers.org/modules/) - a simple lib which would streamline configuring and starting an `azure-app-configuration-emulator` container in the context of complex tests.


- Follow the previous points, it would probably by important to provide more extensive guidance and code examples for using your emulator with Microsoft Entra Id.

**Comment by tnc1997** [comment]
> I would recommend removing the following two lines:
> 
> https://github.com/tnc1997/azure-app-configuration-emulator/blob/fa6514cec07d8a0a61eaf9c07cd5a86bc015e090/src/AzureAppConfigurationEmulator/Program.cs#L37-L38
> 
> My justification is:
> 
> * [`ValidateAudience`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateaudience?view=msal-web-dotnet-latest#remarks) and [`ValidateIssuer`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateissuer?view=msal-web-dotnet-latest#remarks) are `true` by default.
> * Overriding them in this manner prevents a user from setting them to `false` should they want to.
> 
> > **NOTE**: It was not initially obvious to me what the `Audience` and `Issuer` should be.

I would like to retain these two lines because the audience is a [static value](https://learn.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-azure-ad#audience) and the issuer is automatically determined from the discovery document that is based on the `MetadataAddress` for the Microsoft Entra tenant. That being said I have moved the `ValidAudience` into `appsettings.json` to allow it to optionally be overridden to e.g. https://contoso.azconfig.io if desired. It is also worth noting that `ValidateAudience` and `ValidateIssuer` are set by `JwtBearerConfigureOptions` based on the presence of one or more [`audiences`](https://github.com/dotnet/aspnetcore/blob/1ed83e94ba6d3739035fda40f539545a9fceacc3/src/Security/Authentication/JwtBearer/src/JwtBearerConfigureOptions.cs#L69) and one or more [`issuers`](https://github.com/dotnet/aspnetcore/blob/1ed83e94ba6d3739035fda40f539545a9fceacc3/src/Security/Authentication/JwtBearer/src/JwtBearerConfigureOptions.cs#L66) respectively.

**Comment by tnc1997** [comment]
> * Using the official [`ConfigurationClient`](https://learn.microsoft.com/en-us/dotnet/api/azure.data.appconfiguration.configurationclient?view=azure-dotnet) with Entra Id authentication turned out to be non-trivial. I had solve the following challenges:

Unfortunately this is one of the issues of using an emulated Azure resource with a genuine Microsoft Entra tenant. The genuine Microsoft Entra tenant will not have any knowledge of the emulated Azure resource. This is likely one of the reasons that the Azure Cosmos DB emulator for example only allows authentication using a key and not Microsoft Entra ID.

**Comment by tnc1997** [comment]
> I would love to find a better way to solve this issue.

This is not necessarily a better way to solve the issue, but if you are emulating a genuine Azure App Configuration resource, then you could alternatively configure the emulator as if it is the genuine Azure App Configuration resource:

```shell
openssl req -x509 -out ./emulator.crt -keyout ./emulator.key -newkey rsa:2048 -nodes -sha256 -subj '/CN=contoso.azconfig.io' -addext 'subjectAltName=DNS:contoso.azconfig.io'
```

```csharp
using Azure.Data.AppConfiguration;
using Azure.Identity;

var tenantId = Environment.GetEnvironmentVariable("Authentication__Schemes__MicrosoftEntraId__TenantId")!;
var clientId = Environment.GetEnvironmentVariable("Authentication__Schemes__MicrosoftEntraId__ClientId")!;
var clientSecret = Environment.GetEnvironmentVariable("Authentication__Schemes__MicrosoftEntraId__ClientSecret")!;
var credential = new ClientSecretCredential(tenantId, clientId, clientSecret);

var endpoint = Environment.GetEnvironmentVariable("AzureAppConfiguration__Endpoint")!;
var client = new ConfigurationClient(new Uri(endpoint), credential);

var setting = new ConfigurationSetting("AzureAppConfigurationEmulator", "Hello World");
await client.SetConfigurationSettingAsync(setting);
```

```yaml
services:
  azure-app-configuration-emulator:
    build:
      context: https://github.com/tnc1997/azure-app-configuration-emulator.git
      dockerfile: ./src/AzureAppConfigurationEmulator/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - Authentication__Schemes__MicrosoftEntraId__MetadataAddress=https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0/.well-known/openid-configuration
      - Authentication__Schemes__MicrosoftEntraId__ValidAudience=https://contoso.azconfig.io
    networks:
      default:
        aliases:
          - contoso.azconfig.io
    volumes:
      - ./emulator.crt:/usr/local/share/azureappconfigurationemulator/emulator.crt:ro
      - ./emulator.key:/usr/local/share/azureappconfigurationemulator/emulator.key:ro
  console-application:
    build: .
    depends_on:
      - azure-app-configuration-emulator
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet ConsoleApplication.dll"
    environment:
      - Authentication__Schemes__MicrosoftEntraId__ClientId
      - Authentication__Schemes__MicrosoftEntraId__ClientSecret
      - Authentication__Schemes__MicrosoftEntraId__TenantId=00000000-0000-0000-0000-000000000000
      - AzureAppConfiguration__Endpoint=https://contoso.azconfig.io
    volumes:
      - ./emulator.crt:/usr/local/share/ca-certificates/emulator.crt:ro
```
